#!/bin/bash


. ./config


mkdir -p ./config-drives/vm1-config ./config-drives/vm2-config

echo "instance-id: iid-${VM1_NAME}
local-hostname: $VM1_NAME
" >./config-drives/vm1-config/meta-data

echo "instance-id: iid-${VM2_NAME}
local-hostname: $VM2_NAME
" >./config-drives/vm2-config/meta-data




echo "#cloud-config
#ssh_svcname: ssh
runcmd:
  - ip link set $VM1_MANAGEMENT_IF down && ip link set $VM1_MANAGEMENT_IF up
  - ip addr add $VM1_MANAGEMENT_IP/$MANAGEMENT_NET_MASK dev $VM1_MANAGEMENT_IF

" > ./config-drives/vm1-config/user-data


echo "#cloud-config
#ssh_svcname: ssh
runcmd:
  - ip link set $VM2_MANAGEMENT_IF down && ip link set $VM2_MANAGEMENT_IF up
  - ip addr add $VM2_MANAGEMENT_IP/$MANAGEMENT_NET_MASK dev $VM2_MANAGEMENT_IF
" > ./config-drives/vm2-config/user-data

mkisofs -R -V cidata -joliet -o $VM1_CONFIG_ISO ./config-drives/vm1-config
mkisofs -R -V cidata -joliet -o $VM2_CONFIG_ISO ./config-drives/vm2-config
