#!/bin/bash


. ./config
mkdir ./networks

MAC=52:54:00:`(date; cat /proc/interrupts) | md5sum | sed -r 's/^(.{6}).*$/\1/; s/([0-9a-f]{2})/\1:/g; s/:$//;'`


#making templates fot lib networks
echo "
<network>
    <name>$INTERNAL_NET_NAME</name>
    <bridge name='internalbr' />
</network>
" > ./networks/${INTERNAL_NET_NAME}.xml

echo "
<network>
    <name>$MANAGEMENT_NET_NAME</name>
    <bridge name='managementbr' />
    <forward mode='route'/>
    <ip address='$MANAGEMENT_HOST_IP' netmask='$MANAGEMENT_NET_MASK' />
</network>
" > ./networks/${MANAGEMENT_NET_NAME}.xml

echo "
<network>
    <name>$EXTERNAL_NET_NAME</name>
    <bridge name='externalbr' />
    <ip address='$EXTERNAL_NET_HOST_IP' netmask='$EXTERNAL_NET_MASK'>
    <forward mode='nat' />
        <dhcp>
            <range start='$VM1_EXTERNAL_IP' end='$VM1_EXTERNAL_IP' />
         <host mac='$MAC' name='$VM1_NAME' ip='$VM1_EXTERNAL_IP'/>

</dhcp>
    </ip>
</network>
" > ./networks/${EXTERNAL_NET_NAME}.xml

#creating networks from templates
virsh net-define ./networks/${INTERNAL_NET_NAME}.xml
virsh net-define ./networks/${MANAGEMENT_NET_NAME}.xml
virsh net-define ./networks/${EXTERNAL_NET_NAME}.xml

virsh net-start $INTERNAL_NET_NAME
virsh net-start $EXTERNAL_NET_NAME
virsh net-start $MANAGEMENT_NET_NAME

virsh net-autostart $INTERNAL_NET_NAME
virsh net-autostart $EXTERNAL_NET_NAME
virsh net-autostart $MANAGEMENT_NET_NAME


