#!/bin/bash


brctl addbr internalbr
brctl addbr managementbr
brctl addbr externalbr

brctl addif internalbr intern
brctl addif managementbr manage
brctl addif externalbr extern

ifconfig managementbr 192.168.100.1 netmask 255.255.255.0
ifconfig externalbr 192.168.110.1 netmask 255.255.255.0
ifconfig internalbr up
ifconfig managementbr up
ifconfig externalbr up

echo "
<network>
    <name>internal</name>
    <bridge name="internalbr" />
</network>
" > /home/test/internal_template.xml

echo "
<network>
    <name>management</name>
    <bridge name="managementbr" />
    <forward mode="route"/>
    <ip address="192.168.100.1" netmask="255.255.255.0">
        <dhcp>
            <range start="192.168.100.101" end="192.168.100.201" />
        </dhcp>
    </ip>
</network>
" > /home/test/management_template.xml

echo "
<network>
    <name>external</name>
    <bridge name="externalbr" />
    <ip address="192.168.110.1" netmask="255.255.255.0">
        <dhcp>
            <range start="192.168.110.101" end="192.168.110.201" />
        </dhcp>
    </ip>
</network>
" > /home/test/external_template.xml

virsh net-create /home/test/internal_template.xml
virsh net-create /home/test/management_template.xml
virsh net-create /home/test/management_template.xml

